### PR TITLE
Fix typos ch03

### PR DESCRIPTION
**Pull request by PatrickZGW**
A couple of things I'd like your opinion on:

- Should it be "Bitcoin Network" or "Bitcoin network"? In my opinion "Bitcoin network" is correct, because the network is not part of the official name. Otherwise we would also have to write "Bitcoin Transaction", "Bitcoin Code", etc.
- What is the correct capitalization of "Onion"? I didn't change those because I wasn't sure what version is correct. I just think it should ever be  consistently capitalized or not.

### CODE REVIEW

**Comment by bolatovumar** [comment]
@PatrickLemke it should be `Bitcoin network` and `onion routing` IMO. See usage in Wikipedia for example: https://en.wikipedia.org/wiki/Onion_routing

**Comment by aantonop** [comment]
@PatrickLemke If you can fix the conflicts, ready to merge this!

**Comment by PatrickZGW** [comment]
I think the Travis CI build is still failing because of an issue in another file? Should this be fixed in this PR or can this be merged as is?

**Comment by aantonop** [comment]
Merge as is as soon as deconflicted

**Comment by PatrickZGW** [comment]
Merge conflicts should be resolved.

**Pull request merged**
