### PR TITLE
Fixes for issues #655, #572, #624

### PR DESCRIPTION
**Pull request by misbach**
Fixes for issues #655, #572, #624. Also includes a small type fix.

### CODE REVIEW

**Comment by misbach** [comment]
Sorry for the multiple file pull request. I intended to keep this PR to just fixes in routing.asciidoc but github auto-magically combined my PRs into one.

**Comment by giovannizotta** [comment]
Hi there. Commit d1b4bc6 should fix issue #655, if you want to add that into the description. However, in the images directory I do not see a file named dina-routing-diagram.png, so I'm not sure this completely fixes the problem.

**Comment by misbach** [comment]
@GiovanniZotta Thanks for the comment. I have a file named dina-routing-diagram.png in the PR.
It's here: https://github.com/lnbook/lnbook/blob/302f82377587fa35227a9dfc995e92e859ec79a4/images/dina-routing-diagram.png

**Comment by giovannizotta** [comment]
Apologies @misbach, I did not realize that. Awesome!

**Review by renepickhardt — APPROVED** [review]

**Comment by misbach** [comment]
Thank you @renepickhardt

**Pull request merged**
