### PR TITLE
Routing - Introduction (Language Edits and Added a Diagram)

### PR DESCRIPTION
**Pull request by ImranLorgat**

### CODE REVIEW

**Comment by ImranLorgat** [comment]
Source file for the Gloria Routing Diagram. It's in Word lol. I'm sure you'll make a better one come the final release.

[Gloria Routing Diagram.docx](https://github.com/lnbook/lnbook/files/5130928/Gloria.Routing.Diagram.docx)

**Comment by aantonop** [comment]
We will need to hold this, as @Roasbeef has been working on an extensive set of edits to this chapter, creating potential conflicts. Initial merge expected in 2 days, so let's see if we can add this then.

**Comment by ImranLorgat** [comment]
@aantonop now that #350 is merged what becomes of #369 and #370?

Still usable? Or need to be reworked?

**Comment by aantonop** [comment]
Just fix the conflicts @ImranLorgat please

**Comment by ImranLorgat** [comment]
Found it was easier to scrap this and replace it with a fresh PR #498

**Pull request closed without merging**
