### PR TITLE
node_operations: fees: BUG, wrong math

### PR DESCRIPTION
**Pull request by 8go**
- "millionths per satoshi" ==> it is a rate, so it is just "millionths". Just like interest rate is 2% and not "2% per $" or "2%/$"
- rephrased and highlighted to make it more clear, more easy to follow
- changed 100,000 amount to 1,000,000 solely that at the end F_base and F_rate*P are different (different numbers make a better example)
- there was a BUG: in given example F_rate is 1 (not 100), correct total was 2 and not 101 as presented
- "F_rate = 10/1,000,000 * payment size" ==> wrong: ==> F_rate = 10/1,000,000 is correct
- put ( ) around F_rate * P to make it extra clear
- \Rightarrow is NOT showing correctly in "Preview" window, not sure why, \Rightarrow is correct Latex but not shown correctly here. I did not touch it. Maybe this is handled by post-processing.

### CODE REVIEW

**Comment by rene78** [comment]
Ooops, I'm afraid there are some conflicting edits now. I was a little quicker than you https://github.com/lnbook/lnbook/pull/486.

**Comment by 8go** [comment]
Sorry, I had not looked at #486. Between all of us we will work it out :)

**Comment by aantonop** [comment]
Please de-conflict @8go

**Comment by 8go** [comment]
@aantonop : Conflict resolved and I added some tiny-tiny additions to make it even more clear.
All of @rene78 changes were merged in. Thanks Rene. Liked the ppm notation.

**Pull request merged**
