### PR TITLE
travis: Add automatic spell checking of new pull requests using codespell

### PR DESCRIPTION
**Pull request by practicalswift**
Add automatic spell checking of new pull requests using `codespell`.

This will catch most typos before merge :-)

### CODE REVIEW

**Review by renepickhardt — COMMENTED** [review]
I never worked with Travis on github. Do we need to set anything up or is the `.yml` file sufficient for everything to work smoothly?

Other than that super useful suggestion!

**Comment by practicalswift** [comment]
@renepickhardt The `.travis.yml` is all it takes but the owner of the repo will have to enable [activate Travis integration for the repo](https://docs.travis-ci.com/user/tutorial/).

**Comment by bitcoina** [comment]
Wow, didn't know you could do this.  Sound cool!

**Comment by renepickhardt** [comment]
Merged but I can't set up travis as currently only @aantonop has sufficient rights on this git repo / account

**Pull request merged**
