### PR TITLE
Made small grammar corrections to chapters 7, 8, 9, 10, and 11

### PR DESCRIPTION
**Pull request by Randy808**
It's easier for me to review commits all in one go myself, so I bundled all my grammar edits in this PR. Let me know if you'd like me to separate out commits by chapter.

### CODE REVIEW

**Comment by Randy808** [comment]
It's easier for me to review commits all in one go myself, so I bundled all my grammar edits in this PR. Let me know if you'd like me to separate out commits by chapter.

**Comment by Roasbeef** [comment]
Care to rebase this?

**Comment by Randy808** [comment]
Rebased 👌

**Comment by aantonop** [comment]
Nice work!

**Pull request merged**
