### PR TITLE
add "Ligtning Messages" section

### PR DESCRIPTION
**Pull request by 0xmountaintop**
I have to admit the "Lightning Messages" section I add in this PR still seems insubstantial. Would like to hear from @renepickhardt for your suggestions on skeleton

### CODE REVIEW

**Comment by 0xmountaintop** [comment]
Not sure whether I should add "it's ok to be odd". will that be too detailed?

**Review by renepickhardt — COMMENTED** [review]
While I certainly want to talk about Lightning messages and also about the "it's OK to be odd" rule I think this is too early / technical in the sense that chapter 3 is supposed to give a rough overfiew. A lot of the stuff that I have written so far seems rather too technical at this time and for this chapter. I suggest to move the paragraph to a new file maybe named lightning messages so that we can reuse it later when it fits the planned narrative.

**Comment by 0xmountaintop** [comment]
> While I certainly want to talk about Lightning messages and also about the "it's OK to be odd" rule I think this is too early / technical in the sense that chapter 3 is supposed to give a rough overfiew. A lot of the stuff that I have written so far seems rather too technical at this time and for this chapter. I suggest to move the paragraph to a new file maybe named lightning messages so that we can reuse it later when it fits the planned narrative.

Yep I definitively agree. And FYI currently it's in communications_protocol chapter, instead of chap03. :P

**Comment by 0xmountaintop** [comment]
Hi @renepickhardt , that's my idea for the "Ligtning Messages" section, can you take a look again please? Thanks!

**Review by renepickhardt — COMMENTED** [review]
The inormation is correct but I pull @Roasbeef into the discussion for the sake of how deep do we want to go into Lightning messages

**Comment by aantonop** [comment]
Thanks @HAOYUatHZ, sorry for the delay!

**Pull request merged**
