### PR TITLE
`all Bitcoin` -> `all bitcoins`

### PR DESCRIPTION
**Pull request by nopara73**
I'm pretty sure I've read the correct pluralization and capitalization in the Mastering Bitcoin book a long time ago.

### CODE REVIEW

**Review by renepickhardt — COMMENTED** [review]
when do we write bitcoin with a capital B and when with a lowercase b? is it as soon was we speek of the concret monetary unit of exchange / the token the letter b will be lower case whereas if we refer to the name of the protocol / currency the latter will be capitalized?

**Comment by ugamkamat** [comment]
@renepickhardt yes, Bitcoin with capital B is generally used to represent technology, while bitcoins with small b is used to represent currency. There is an interesting discussion on bitcoin meta stackexchange on this [here](https://bitcoin.meta.stackexchange.com/questions/21/how-do-we-capitalize-bitcoin-or-bitcoin-or-bitcoin).

**Comment by renepickhardt** [comment]
Then there would still remain the question for plural s. Is it 5 bitcoin or 5 bitcoins?

**Comment by ugamkamat** [comment]
When referring as a currency (bitcoins), I think the convention should be the same as dollars.

**Comment by wombat26** [comment]
_Bitcoin_ (with capital B) is normally uses to refer to the whole protocol, technology, network, etc.

_bitcoin_ ( with lower b) is normally uses to name the digital token unit, the coin, the currency. On the economic / trading jargon people often says 0.5 bitcoin, 1 bitcoin, 2 bitcoin, 10 bitcoin.

In _"Mastering Bitcoin"_  is used _bitcoin_ with lower b and singular to refer to any amount of bitcoin. Even if a prefix is used the singular mode remains e.g. 100 millibitcoin 

On the other hand, the word _satoshi_ is used in singular and plural,
1 satoshi, 5 satoshis, 100 satoshis.

_My name is Anibal Santaella, a pleasure to be here._

**Comment by wombat26** [comment]
> Then there would still remain the question for plural s. Is it 5 bitcoin or 5 bitcoins?
In _"Mastering Bitcoin"_  is used bitcoin with lower b and singular to refer to any amount of bitcoin.  
Even if a prefix is used the singular mode remains e.g. 100 millibitcoin.

**Comment by nopara73** [comment]
Maybe always plural, except when at 1 BTC?

- 0.1 bitcoins
- 1 bitcoin
- 1.1 bitcoins
- 21,000,000 bitcoins

**Comment by renepickhardt** [comment]
other currencies don't have a plural when being added as a unit. 

I say this costs 5 Euro or 5 Dollar. I don't say 5 Euros or 5 Dollars. would only use the plural if I have several coins / bills in my pocket but I am not even sure if that was colloquial. In bitcoin this situation would not really have an equivalent unless I would refer to several UTXOs which I guess noone ever did when utilizing the plural s or not (as the UTXOs are hardly visible to the user)

Still hesitant to merge because there still seems to be a disagreement about plural.

**Comment by wombat26** [comment]
I think we have to keep on mind the economy, simplicity, syntax of the language while stablishing these definitions.

**Comment by ugamkamat** [comment]
@renepickhardt I disagree. We say "the coffee cost me $2 dollars" rather than "the coffee cost me 2 dollar". The use of plural depends crucially on whether the phrase is prenominal (placed before a noun) or not. I tried to search something on a sister stackexchange site to back my reasoning. Found one [here](https://ell.stackexchange.com/questions/104829/correct-way-to-express-monetary-loss-dollar-vs-dollars)

**Comment by nopara73** [comment]
> Still hesitant to merge because there still seems to be a disagreement about plural.

I'm not insisting on my pluralization, so I'll wait for the decision.

**Comment by PatrickZGW** [comment]
Using currencies without a plural is the standard way in other languages like German. In English the plural sounds more natural to me.

**Comment by Chriton** [comment]
I found this pdf here https://www.oecd-ilibrary.org/economics/oecd-style-guide_9789264243439-en. At pages 70-73 they have examples of different currencyes and their plural. Usually currencies have a plural form which is different from the singular.
Also another article is here http://www.amigaforever.com/kb/13-144. See the **Singular vs. Plural Form** section.

**Comment by aantonop** [comment]
I prefer the singular form, as bitcoin is intangible and based on arbitrary sized UTXO values. This make me think it should be treated as an uncountable noun, rather than a noun describing discreet units. 

I used this convention (mostly but not 100% consistently) in Mastering Bitcoin and would like to continue to use it here:

1 bitcoin
2 bitcoin
many bitcoin
She sent all of her bitcoin to Bob
There will only ever be less than 21 million bitcoin
I have 3.2 bitcoin

etc.

**Pull request closed without merging**
