### PR TITLE
Update c-lightning docker version

### PR DESCRIPTION
**Pull request by kevin-miller-0405**
I got an error complaining the c-lightning version doesn't exist when trying out the example following chapter 4.
By updating to the latest version, I was able to get the example working.

### CODE REVIEW

**Comment by renepickhardt** [comment]
I cannot verify / test this right now. @aantonop could you help out please?

**Comment by rajarshimaitra** [comment]
Can confirm. The issue is there, and the above patch fixes it.

**Comment by Bosch-0** [comment]
Also experienced this error and can confirm this PR fixes it. c-lightning 0.10.1 is out now so may want to update to that.

**Comment by sbddesign** [comment]
This fix worked for me!

**Comment by aantonop** [comment]
A complete rewrite of the Docker configs and scripts has happened. Everything should work more consistently now with the latest versions

**Pull request closed without merging**
