### PR TITLE
Replace "wallet" with "address", in relation to hashcash's unilateral channel proposal.

### PR DESCRIPTION
**Pull request by bitcoina**
Propose to replace the comment regarding multi-sig wallet, with multi-sig transaction.

### CODE REVIEW

**Review by renepickhardt — CHANGES_REQUESTED** [review]
the transaction is not funded. so I reject this. instead wallet we could say address. I agree that wallet is not the most specific tearm

**Comment by bitcoina** [comment]
Learning stuff here.... :) - its fun..

i.e.  how a multisig address is created and how you fund it.  Thanks,

**Review by renepickhardt — APPROVED** [review]
will be hard for me in future. as I usually use the term multisignature wallet but I guess in this case multisignature address is just more accurate (: 

it is by the way hashcoins unilateral channel proposal :P

**Comment by bitcoina** [comment]
Glad you are keeping us all honest :)

**Pull request merged**
