### PR TITLE
Security and Privacy - Private Channels

### PR DESCRIPTION
**Pull request by ImranLorgat**
Clarified and expanded section on Private Channels

### CODE REVIEW

**Review by renepickhardt — CHANGES_REQUESTED** [review]
I am actually not sure if we should / want to call them private channels. it has been pointed out several times that they are much more `unannounced` and I think this is where the terminology among lightning devs is heading.

**Comment by ImranLorgat** [comment]
Noted. Updated this section and expanded a little with privacy caveats.

Not sure what happened to the chapter. It doesn't seem to be in the repo anymore.

**Comment by renepickhardt** [comment]
It's been moved to contrib folder. I think the idea was to have everything that is still WIP in contrib. Can you confirm @aantonop ?

**Comment by ImranLorgat** [comment]
I see it's there. Link below. Are you able to merge the changes into the moved file, or do I need to open another pull request?

https://github.com/lnbook/lnbook/blob/develop/contrib/security_privacy_ln.asciidoc#private-channels

**Comment by ImranLorgat** [comment]
@aantonop @renepickhardt I'm following up on this

I see Chapter 13 is marked as "published as an early draft". The section on private channels still refers to them as "private" instead of as "unannounced" and is the original brief section. Have the changes in this pull request been rejected?

https://github.com/lnbook/lnbook/blob/develop/13_security_privacy_ln.asciidoc#private-channels

**Comment by Roasbeef** [comment]
Can you rebase this? The text has shifted slightly, and it's also now chapter 15.

**Pull request closed without merging**
