### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Review by nopara73 — APPROVED** [review]

**Comment by practicalswift** [comment]
The following additional typos have to be fixed before Travis CI is happy :)

```
$ codespell --ignore-words-list=que $(git ls-files -- "*.asciidoc" "*.md")
ch01.asciidoc:28: verisons  ==> versions
ch01.asciidoc:37: enforcable  ==> enforceable
ch01.asciidoc:38: claimes  ==> claims
ch01.asciidoc:67: todays  ==> today's  | disabled because of var names
ch01.asciidoc:67: todays  ==> today's  | disabled because of var names
ch01.asciidoc:89: refered  ==> referred
ch01.asciidoc:90: refered  ==> referred
topics.asciidoc:192: seperately  ==> separately
topics.asciidoc:199: truely  ==> truly
```

**Comment by renepickhardt** [comment]
How can I find the output of Travis on github? I am on mobile right now and clicking on details did not reveal the output of the checks

**Comment by practicalswift** [comment]
@renepickhardt I'm not sure about mobile, but you can reach the Travis output on desktop via:
* Click on "**Details**" to the right of "Travis CI - Pull Request Failing after 32s — Build Failed"
* Then click on "**The build**" in the sentence "The build failed, just like the previous build"
* You are now taken to: https://travis-ci.com/lnbook/lnbook/builds/127736029

**Comment by yahiheb** [comment]
They have been fixed in #60. What should I do to make it build?

**Comment by practicalswift** [comment]
@yahiheb The best way is to rebase on `develop` and force push. Alternatively it might be the case that simply closing and re-opening the PR will do the trick and trigger a new Travis build.

**Comment by yahiheb** [comment]
I think this is not the way to fix that.

**Comment by practicalswift** [comment]
@yahiheb Rebasing can be tricky. Another option could be to simply discard this PR and open a new one with your suggested changes.

**Comment by yahiheb** [comment]
Yes. I will try to fix that (I am still learning) if it doesn't work I will simply close it. Thank you

**Pull request closed without merging**
